server:
  port: 8083

spring:
  #依赖循环引用是不鼓励的，默认情况下是禁止的。更新应用程序以删除bean之间的依赖循环。
  #作为最后的手段，可以通过设置spring.main来自动打破循环。allow-circular-references为true。
  main:
    allow-circular-references: true
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    #单位毫秒
    connect-timeout: 10000
    database: 0
    # 配置lettuce
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 1
        # 连接池中的最大空闲连接
        max-idle: 6
        # 连接池最大连接数（使用负值表示没有限制,不要配置过大，否则可能会影响redis的性能）
        max-active: 10
        # 连接池最大阻塞等待时间（使用负值表示没有限制）；单位毫秒
        max-wait: 1000
      #关闭超时时间；单位毫秒
      shutdown-timeout: 200

  #数据源
#  primary
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.101.17:3306/testdatabase?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
      hibernate:
        #     更新或者创建数据表结构
        ddl-auto: update
      #    控制台显示SQL
      show-sql: true

#mybatis:
#  type-aliases-package: com.jiao.testproject.testproject.entity
#  mapper-locations: classpath:mapper/*.xml , classpath:jiao-mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

debug: true
mybatis-plus:
  configuration:
#    驼峰转换
    map-underscore-to-camel-case: true
    # 返回类型为Map,显示null对应的字段
    call-setters-on-nulls: true
      #   引入分页插件
    interceptor:
      - com.baomidou.mybatisplus.extension.plugins.PaginationInterceptor
    log-impl:  org.apache.ibatis.logging.stdout.StdOutImpl
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.jiao.testproject.testproject.entity
  global-config:
    db-config:
      id-type: assign_id
      # 默认数据库表下划线命名
      table-underline: true
logging:
  config: classpath:logback-spring.xml
pagehelper:
#  dialect: mysql 弃用
  helper-dialect: mysql
  support-methods-arguments: true
  params: countSql

DEFAULT_NAMESRVADDR: 192.168.101.84:9876

